### PR TITLE
feat!: bill on beginning of period & billing period based on start date instead of months

### PR DESCRIPTION
**Pull request by HenningWendtland**
contains two new features:
- added support for billing at the beginning of a period
- added support for billing periods that are based on start date (e.g. do not follow calendar months)

further details:
- should be backwards compatbile to version 15.0.0 (without the new select fields)
- Button "Create invoice for last period" is no "create invoice for current period", acting the same then before but extended to the new cases
- refactor of the function "get_first_day_of_period": now always returns a period (from_date, to_date), calculation simplified, function name changed to "get_calendar_period" since it is more fitting

### CODE REVIEW

**Comment by UsamaNaveed9** [comment]
PR is tested.
Some suggestions will be easier to understand for users.

Case 1:  `Billing Period is based on = "start date" and Billing Time = "at beginning of period"`
image

In this case, the Invoice is  created based on the frequency current period
image

Case 2:  `Billing Period is based on = "calendar months" and Billing Time = "at beginning of period"`
image

In this case, the Invoice is  created based on the frequency current period
image

**The subscription period is based on the current frequency in the above two cases.
So, we can change Billing Time "at beginning of period" to "Current"**

Case 3:  `Billing Period is based on = "start date" and Billing Time = "after end of period"`
image

In this case, the Invoice is created based on the frequency previous period
image

Case 4:  `Billing Period is based on = "calendar months" and Billing Time = "after end of period"`
image

In this case, the Invoice is created based on the frequency previous period
image

**The subscription period is based on the previous frequency in the above two cases.
So, we can change Billing Time "after end of period" to "Previous"**

image

Change the button Label to "Create {Frequency} invoice"

**Review by barredterra — DISMISSED** [review]
Please adjust the current tests and add a test for the new method.

**Comment by HenningWendtland** [comment]
> Please adjust the current tests and add a test for the new method.

Done

**Comment by HenningWendtland** [comment]
@UsamaNaveed9 About your suggestions:
I think changing the values of  the fields "Billing Period is based on" (current: "calendar months"/"start date") 
and "Billing Time" (current: "at beginning of period" / "after end of period")
or merging them is not a good idea

**How it works**

- The "Billing Period is based on" Select triggers if the period is in line with the calendar or with the start date. For example if Start Date = 11-04-2024 in the "calendar month" case the first period will be 01-04-2024 to 30-04-2024
in "start date" case the first period will be 11-04-2024 to 10-05-2024

- The "Billing Time" Select triggers **when** the invoices should be auto generated (via scheduler), which is either at the beginning or after the end of a period, depending on customer preference

- The button "Create Current Monthly Invoice" is intended for allowing the user to test  if the subscription is created correctly, by creating the "current" invoice, e.g. the one that the scheduler would create if running right now. Depending on the above discussed two fields, the dates may vary. In case the scheduler would not create an invoice right now an error message should be displayed

**Review by barredterra — APPROVED** [review]

**Pull request merged**
